package com.example.model

import androidx.compose.ui.graphics.Color

enum class ThemePalette(
    val id: String,
    val displayName: String,
    val backgroundStart: Color,
    val backgroundEnd: Color,
    val boardBackground: Color,
    val boardBorder: Color,
    val gridLineColor: Color,
    val primaryArrowColor: Color,
    val secondaryArrowColor: Color,
    val accentArrowColor: Color,
    val amberArrowColor: Color,
    val exitGlowColor: Color,
    val hintColor: Color,
    val isLight: Boolean = true,
    val pillBackground: Color = Color(0xFFDDE6CD),
    val pillHighlight: Color = Color(0xFFB5F2B1),
    val textPrimary: Color = Color(0xFF191C17),
    val textSecondary: Color = Color(0xFF44483E),
    val tileBackground: Color = Color(0xFFFFFFFF)
) {
    EDITORIAL(
        id = "editorial",
        displayName = "Editorial Sage",
        backgroundStart = Color(0xFFFBFDF8),
        backgroundEnd = Color(0xFFF2F5ED),
        boardBackground = Color(0xFFE2E3DE),
        boardBorder = Color(0xFFC2CDB1),
        gridLineColor = Color(0xFFD3D7CE),
        primaryArrowColor = Color(0xFF386A20),
        secondaryArrowColor = Color(0xFF558B2F),
        accentArrowColor = Color(0xFF2E7D32),
        amberArrowColor = Color(0xFFE65100),
        exitGlowColor = Color(0xFFB5F2B1),
        hintColor = Color(0xFFE6A700),
        isLight = true,
        pillBackground = Color(0xFFDDE6CD),
        pillHighlight = Color(0xFFB5F2B1),
        textPrimary = Color(0xFF191C17),
        textSecondary = Color(0xFF44483E),
        tileBackground = Color(0xFFFFFFFF)
    ),
    TERRACOTTA(
        id = "terracotta",
        displayName = "Editorial Terracotta",
        backgroundStart = Color(0xFFFCF9F6),
        backgroundEnd = Color(0xFFF5EFEB),
        boardBackground = Color(0xFFEBE3DD),
        boardBorder = Color(0xFFDCBFB3),
        gridLineColor = Color(0xFFDFD4CC),
        primaryArrowColor = Color(0xFF9E472A),
        secondaryArrowColor = Color(0xFFBF5F3B),
        accentArrowColor = Color(0xFF8D3B20),
        amberArrowColor = Color(0xFFD97706),
        exitGlowColor = Color(0xFFFFDBCF),
        hintColor = Color(0xFFD97706),
        isLight = true,
        pillBackground = Color(0xFFF0DDD6),
        pillHighlight = Color(0xFFFFDBCF),
        textPrimary = Color(0xFF231A16),
        textSecondary = Color(0xFF53433D),
        tileBackground = Color(0xFFFFFFFF)
    ),
    NORDIC_SLATE(
        id = "nordic_slate",
        displayName = "Editorial Slate",
        backgroundStart = Color(0xFFF8F9FA),
        backgroundEnd = Color(0xFFECEEF1),
        boardBackground = Color(0xFFDEE2E6),
        boardBorder = Color(0xFFBAC2CB),
        gridLineColor = Color(0xFFCFD5DC),
        primaryArrowColor = Color(0xFF2C4A6F),
        secondaryArrowColor = Color(0xFF3D6594),
        accentArrowColor = Color(0xFF1B365D),
        amberArrowColor = Color(0xFFE67E22),
        exitGlowColor = Color(0xFFD0E1F9),
        hintColor = Color(0xFFF39C12),
        isLight = true,
        pillBackground = Color(0xFFDCE3ED),
        pillHighlight = Color(0xFFD0E1F9),
        textPrimary = Color(0xFF141D26),
        textSecondary = Color(0xFF404E5C),
        tileBackground = Color(0xFFFFFFFF)
    ),
    MIDNIGHT_INK(
        id = "midnight_ink",
        displayName = "Editorial Ink",
        backgroundStart = Color(0xFF191C17),
        backgroundEnd = Color(0xFF21261E),
        boardBackground = Color(0xFF2B3227),
        boardBorder = Color(0xFF3E4A38),
        gridLineColor = Color(0xFF353E31),
        primaryArrowColor = Color(0xFFB5F2B1),
        secondaryArrowColor = Color(0xFF9BD996),
        accentArrowColor = Color(0xFF81C784),
        amberArrowColor = Color(0xFFFFCC80),
        exitGlowColor = Color(0xFF386A20),
        hintColor = Color(0xFFFFE082),
        isLight = false,
        pillBackground = Color(0xFF384333),
        pillHighlight = Color(0xFF386A20),
        textPrimary = Color(0xFFFBFDF8),
        textSecondary = Color(0xFFC2CDB1),
        tileBackground = Color(0xFF20261D)
    ),
    NEON_CYBER(
        id = "neon_cyber",
        displayName = "Neon Cyber",
        backgroundStart = Color(0xFF0D1117),
        backgroundEnd = Color(0xFF161B22),
        boardBackground = Color(0xFF1F242C),
        boardBorder = Color(0xFF388BFD),
        gridLineColor = Color(0xFF30363D),
        primaryArrowColor = Color(0xFF00E5FF),
        secondaryArrowColor = Color(0xFFFF2A6D),
        accentArrowColor = Color(0xFF05D5FA),
        amberArrowColor = Color(0xFFFFB800),
        exitGlowColor = Color(0xFF00F5D4),
        hintColor = Color(0xFFFFE600),
        isLight = false,
        pillBackground = Color(0xFF2D333B),
        pillHighlight = Color(0xFF00E5FF).copy(alpha = 0.2f),
        textPrimary = Color(0xFFFFFFFF),
        textSecondary = Color(0xFF8B949E),
        tileBackground = Color(0xFF161B22)
    )
}

